queue_rules:
  - name: default
    queue_conditions:
      - base=main
      - status-success="check c bindings"
      - status-success="check python bindings (ubuntu-latest, 3.8)"
      - status-success="check-code-format"
      - label=status-merge-when-passing
      - label!=status-work-in-progress
      - "approved-reviews-by=@flux-framework/pfa"
      - "#approved-reviews-by>0"
      - "#changes-requested-reviews-by=0"
      - -title~=^\[*[Ww][Ii][Pp]
    merge_conditions:
      # conditions for a PR to get merged (i.e., out of the queue)
      - base=main
      - status-success="check c bindings"
      - status-success="check python bindings (ubuntu-latest, 3.8)"
      - status-success="check-code-format"
    update_method: rebase
    merge_method: merge

pull_request_rules:
  - name: remove approved reviews when updated
    conditions:
      # conditions for approving reviews to be removed
      - author!=@flux-framework/pfa
    actions:
      dismiss_reviews:
        approved: true
        changes_requested: false
        message: |
          All approving reviews have been removed because this pull request
          was updated.
  - name: rebase and merge when passing all checks
    conditions: []
    actions:
      queue:
