name: build PerfFlowAspect

on:

  # Publish packages on release
  release:
    types: [published]

  # We might want to remove this, OR provide a base container
  # that will more quickly build from, or use cache
  pull_request: []

  # On push to main we build and deploy images
  push:
    branches:
    - main

jobs:
  build:
    env:
      container: ghcr.io/flux-framework/perf-flow-aspect
    permissions:
      packages: write

    runs-on: ubuntu-latest
    name: Build
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Make Space For Build
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc

    - name: Pull Layers
      run: docker pull ${{ env.container }}:latest || echo "No layers to pull"

    - name: Build Container
      run: docker build -t ${{ env.container }}:latest .

    - name: GHCR Login
      if: (github.event_name != 'pull_request')
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Tag and Push Release Image
      if: (github.event_name == 'release')
      run: |
        tag=${GITHUB_REF#refs/tags/}
        echo "Tagging and releasing ${{ env.container }}:${tag}"
        docker tag ${{ env.container }}:latest ${{ env.container }}:${tag}
        docker push ${{ env.container }}:${tag}

    - name: Deploy
      if: (github.event_name != 'pull_request')
      run: docker push ${{ env.container }}:latest
